[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Proxy API calls to SPEAR backend to avoid mixed content
[[redirects]]
  from = "/spear/*"
  to = "http://13.229.75.142:8080/:splat"
  status = 200
  force = true

# SPA redirects so client routes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
